language: java
install: true


dist: trusty
jdk:
  - openjdk8
  - openjdk13

matrix:
  allow_failures:
    - jdk: openjdk-ea

branches:
  only:
  - master
 
script:
  - echo $JAVA_HOME
  - java -version
  - ./gradlew --continue build -s -p modules/