language: java
install: true


dist: trusty
jdk:
  - openjdk13

matrix:
  allow_failures:
    - jdk: openjdk-ea

branches:
  only:
  - master
 
script:
  - echo $JAVA_HOME
  - java -version
  - ./gradlew :modules:percolator:build :modules:percolator:test :modules:rank-eval:build :modules:rank-eval:test :modules:ingest-geoip:build :modules:ingest-geoip:test :modules:parent-join:build :modules:parent-join:test
  
  