language: java
install: true


dist: trusty
jdk:
  - oraclejdk11

matrix:
  allow_failures:
    - jdk: openjdk-ea

branches:
  only:
  - master
 
script:
  - echo $JAVA_HOME
  - java -version
  - ./gradlew --continue clean build --scan -s -p modules/