language: java
install: true


dist: trusty
jdk:
  - oraclejdk8

matrix:
  allow_failures:
    - jdk: openjdk-ea

branches:
  only:
  - master
 
before_script:
  - echo $JAVA_HOME
  - java -version
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

script:
  - java -version
  - ./gradlew --continue clean build --scan -s -p modules/